Indent with spaces instead of tabs

diff --git a/link/.local/bin/rand-stars b/link/.local/bin/rand-stars
--- a/link/.local/bin/rand-stars
+++ b/link/.local/bin/rand-stars
@@ -18,14 +18,14 @@ DEFAULT_VERBOSE=false
 
 while getopts 'fp:r:v' OPTION
 do
-	case $OPTION in
-		f) FORCE=true ;;
-		p) POW="$OPTARG" ;;
-		r) RES="$OPTARG" ;;
-		v) VERBOSE=true ;;
-		\?) exit 1 ;;
-		*) ;;
-	esac
+    case $OPTION in
+        f) FORCE=true ;;
+        p) POW="$OPTARG" ;;
+        r) RES="$OPTARG" ;;
+        v) VERBOSE=true ;;
+        \?) exit 1 ;;
+        *) ;;
+    esac
 done
 
 shift $((OPTIND - 1)) || exit
@@ -34,36 +34,36 @@ OUTFILE="$1"
 
 if [ -z "$OUTFILE" ]
 then
-	echo 'Error: output image path not given' 1>&2
-	exit 1
+    echo 'Error: output image path not given' 1>&2
+    exit 1
 fi
 
 if [ -e "$OUTFILE" ]
 then
-	if ! $FORCE
-	then
-		echo 'Error: output image path already exists' 1>&2
-		exit 1
-	fi
+    if ! $FORCE
+    then
+        echo 'Error: output image path already exists' 1>&2
+        exit 1
+    fi
 fi
 
 if ! command -v magick > /dev/null
 then
-	echo 'Error: "magick" command not found' 1>&2
-	exit 1
+    echo 'Error: "magick" command not found' 1>&2
+    exit 1
 fi
 
 if $VERBOSE
 then
-	set -x
+    set -x
 fi
 
 magick \
-	-size "$RES" \
-	canvas:black \
-	-colorspace Gray \
-	+noise Laplacian \
-	-evaluate Pow "$POW" \
-	-normalize \
-	-depth 4 \
-	"$OUTFILE"
+    -size "$RES" \
+    canvas:black \
+    -colorspace Gray \
+    +noise Laplacian \
+    -evaluate Pow "$POW" \
+    -normalize \
+    -depth 4 \
+    "$OUTFILE"
diff --git a/link/.local/bin/update-weather b/link/.local/bin/update-weather
--- a/link/.local/bin/update-weather
+++ b/link/.local/bin/update-weather
@@ -6,14 +6,14 @@ declare -r LOCATION_SH="$XDG_RUNTIME_DIR"/location.sh
 
 if [[ -z "$LAT" ]] || [[ -z "$LON" ]]
 then
-	update-location || exit
-	source "$LOCATION_SH" || exit
+    update-location || exit
+    source "$LOCATION_SH" || exit
 
-	if [[ -z "$LAT" ]] || [[ -z "$LON" ]]
-	then
-		echo 'Error: Both LAT and LON must be set'
-		exit 1
-	fi
+    if [[ -z "$LAT" ]] || [[ -z "$LON" ]]
+    then
+        echo 'Error: Both LAT and LON must be set'
+        exit 1
+    fi
 fi
 
 # https://openweathermap.org/current#data
@@ -27,14 +27,14 @@ declare -r WEATHER_JSON="$XDG_RUNTIME_DIR"/openweathermap-org-current.json
 #if [[ ! -f "$WEATHER_JSON" ]] || (( $(date -r "$WEATHER_JSON" +%s) < $(date -d '10 minutes ago' +%s) ))
 if [[ ! -f "$WEATHER_JSON" ]] || (( $(stat --printf %Y -- "$WEATHER_JSON") < EPOCHSECONDS-60*10 ))
 then
-	if [[ -z "$OPENWEATHERMAP_API_KEY" ]]
-	then
-		echo 'Error: Must have OpenWeather API key'
-		echo 'https://openweathermap.org/api'
-		exit 1
-	fi
+    if [[ -z "$OPENWEATHERMAP_API_KEY" ]]
+    then
+        echo 'Error: Must have OpenWeather API key'
+        echo 'https://openweathermap.org/api'
+        exit 1
+    fi
 
-	declare -r WEATHER_URI="https://api.openweathermap.org/data/2.5/weather?lat=${LAT}&lon=${LON}&units=${UNITS}&appid=${OPENWEATHERMAP_API_KEY}"
+    declare -r WEATHER_URI="https://api.openweathermap.org/data/2.5/weather?lat=${LAT}&lon=${LON}&units=${UNITS}&appid=${OPENWEATHERMAP_API_KEY}"
 
-	curl -s -f "$WEATHER_URI" > "$WEATHER_JSON" || exit
+    curl -s -f "$WEATHER_URI" > "$WEATHER_JSON" || exit
 fi
