Handle error when either LAT or LON is still empty

diff --git a/link/.local/bin/update-weather b/link/.local/bin/update-weather
--- a/link/.local/bin/update-weather
+++ b/link/.local/bin/update-weather
@@ -10,6 +10,12 @@ then
 	LAT="${MY_LOCATION[0]}"
 	LON="${MY_LOCATION[1]}"
 	unset MY_LOCATION
+
+	if [[ -z "$LAT" ]] || [[ -z "$LON" ]]
+	then
+		echo 'Error: Both LAT and LON must be set'
+		exit 1
+	fi
 fi
 
 # https://openweathermap.org/current#data
